name: CI

on:
  push:
    tags:
      - "v*.*.*"


jobs:
  ubuntu-latest:
    runs-on: ubuntu-latest
    outputs:
      zip_path: ${{ steps.Build.outputs.zip_path }}
    steps:
      - name: setenv
        id: setenv
        uses: actions/setup-go@v3
        with:
          go-version: '^1.21'
    
      - name: Clone
        uses: actions/checkout@v3

      - name: Build
        id: build
        run: |
          make cmd
          ls build/
          zip -r palworld-linux.zip build/

      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: palworld-linux.zip


  macOS-latest:
    runs-on: macos-latest
    outputs:
      zip_path: ${{ steps.Build.outputs.zip_path }}
    steps:
      - name: setenv
        id: setenv
        uses: actions/setup-go@v3
        with:
          go-version: '^1.21'
          
      - name: Clone
        uses: actions/checkout@v3

      - name: Build
        id: build
        run: |
          make cmd
          ls build/
          zip -r palworld-drawin.zip build/

      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: palworld-drawin.zip

  windows:
    runs-on: windows-latest

    strategy:
      matrix:
        build: [Release]
        arch: [Win32, x64]
        sdl2: [ON]
        include:
          - arch: Win32
            s2arc: x86
          - arch: x64
            s2arc: x64
    
    steps:
      - name: setenv
        uses: actions/setup-go@v3
        with:
          go-version: '^1.21'
          
      - name: Clone
        uses: actions/checkout@v3

      - name: Build
        run: |
          make cmd
          ls build/
          Compress-Archive -Path ./build -DestinationPath palworld-${{ matrix.arch }}.zip
      
      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: palworld-${{ matrix.arch }}.zip
          


  
  release:
    needs: [ubuntu-latest, macOS-latest, windows]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3

      - name: Display structure of downloaded files
        run: ls -R

      - name: Release
        uses: softprops/action-gh-release@v0.1.15
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            artifact/palworld-Win32.zip
            artifact/palworld-drawin.zip
            artifact/palworld-linux.zip
            artifact/palworld-x64.zip